.TH CURSE 6
.SH NAME
curse \- mayhem in the great outdoors!
.SH SYNOPSIS
.B curse
[\fB\-s\fR \fISEED\fR]
[\fB\-m\fR \fIMAP-SHAPE\fR]
.SH DESCRIPTION
.B curse
is a rogue-like game set in the great outdoors.
.SH OPTIONS
.TP
.BI SEED
The seed used to generate the map.
By default a random seed is used.
.TP
.BI MAP-SHAPE
The shape of the map; can be either 'round' or 'band'.
